MODE_MANUAL = 0
MODE_AUTO = 1

WLAN_NAME = "my_WI-FI"
WLAN_KEY = "11111111"

RASPBERRY_0_MAC = "b8-27-eb-54-fc-60"
RASPBERRY_IP = 'localhost'
RASPBERRY_USER = 'pi'
RASPBERRY_PASSWORD = '12345678'
RASPBERRY_SOCKET_PORT = 9091
RASPBERRY_SSH_PORT = 22

RASPBERRY_APP_DIRECTORY = '/home/pi/Connector'

TIMER_INTERVAL = 50    #In milliseconds

DIRECTION_STATUS_STANDING = 0
DIRECTION_STATUS_FORWARD = 1
DIRECTION_STATUS_BACKWARD = 2

ROTATION_STATUS_FRONT = 0
ROTATION_STATUS_LEFT = 1
ROTATION_STATUS_RIGHT = 2
