WLAN_NAME = "my_WI-FI"
WLAN_KEY = "11111111"

RASPBERRY = {
'MAC': "b8-27-eb-54-fc-60",
'username': 'pi',
'password': '12345678',
'socket_port': 9091,
'ssh_port': 22
}

RASPBERRY_SOCKET_PORT = 9091
RASPBERRY_SSH_PORT = 22

RASPBERRY_APP_DIRECTORY = '/home/pi/Connector'

timer_interval = 50

DIRECTION_STATUS_STANDING = 0
DIRECTION_STATUS_FORWARD = 1
DIRECTION_STATUS_BACKWARD = 2

ROTATION_STATUS_FRONT = 0
ROTATION_STATUS_LEFT = 1
ROTATION_STATUS_RIGHT = 2

KEY_PRESSED = 0
KEY_DOWN = 1
KEY_UP = 2
